{
  "Header": {
    "Original": "CVE-2022-48564 (read_ints in plistlib.py in Python through 3.9.1 is vulnerable to a po ...)",
    "ID": "CVE-2022-48564",
    "Description": "(read_ints in plistlib.py in Python through 3.9.1 is vulnerable to a po ...)"
  },
  "Annotations": [
    {
      "Original": "- python3.9 3.9.1~rc1-1",
      "Type": "package",
      "Package": "python3.9",
      "Kind": "fixed",
      "Version": "3.9.1~rc1-1"
    },
    {
      "Original": "- python3.7 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.7",
      "Kind": "removed"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/issues/86269",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/issues/86269"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/34637a0ce21e7261b952fbd9d006474cc29b681f\t(v3.10.0a2)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/34637a0ce21e7261b952fbd9d006474cc29b681f\t(v3.10.0a2)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/e277cb76989958fdbc092bf0b2cb55c43e86610a (3.9)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/e277cb76989958fdbc092bf0b2cb55c43e86610a (3.9)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/225e3659556616ad70186e7efc02baeebfeb5ec4 (v3.7.10)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/225e3659556616ad70186e7efc02baeebfeb5ec4 (v3.7.10)"
    }
  ]
}